services:
  - name: news-api
    type: web
    env: python
    region: singapore 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT news_api:app"
    plan: free 